language: node_js
services:
  - mongodb
node_js:
  - "7.7"
  - "10"
  - "11"
cache:
  directories:
  - "node_modules"
env:
  global:
    - CC_TEST_REPORTER_ID=69e81814a0d02ce213968b29b36c35b136aecba8a93764bcae20c05ffa5fa8fe
    - NODE_ENV=test
    - PORT=5037
    - API_VERSION=v1
    - LOCAL_URL=http://127.0.0.1:3001
    - CT_URL=http://127.0.0.1:9000
    - MONGO_PORT_27017_TCP_ADDR=127.0.0.1
    - CT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm test
  - npm run coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
